### ISSUE TITLE
Performance evaluation

### ISSUE THREAD

**Issue by astamagg** [roemba/xsplit#100]
Stefanie will send us an email about how we can do the performance evaluation. We need to plan it and present our plan in next weeks meeting

**Comment by jwbambacht** [comment]
A performance evaluation should answer these questions:

0. What research question(s)/hypothesis(theses) does this study consider?
1. What metrics are important? (e.g., latency, throughput)
2. What parameters impact these metrics? (e.g., number of participants)
3. Is it possible to vary the parameter values? If yes, what values make
sense for the evaluation?
4. What are the results for the chosen parameter values?
5. Why do the results make sense?
6. What is the impact of these results on future development/research
directions?

Experiments should be repeatable (and documented in such a way that
people can repeat them) as well as repeated sufficiently often to have
statistical significance
