### ISSUE TITLE
Write Implementation and testing

### ISSUE THREAD

**Issue by jeysbach** [roemba/xsplit#40]

**Comment by jeysbach** [comment]
![image](https://user-images.githubusercontent.com/15887323/76304253-5b696500-62c3-11ea-9b76-1a94bbeaa472.png)

**Comment by tomdevman** [comment]
I will write about the database part in the implementation section.

**Comment by tomdevman** [comment]
Added the database part in the report. Let me know what you guys think and if I should add more to it.

**Comment by roemba** [comment]
I added (what I think are) the last parts of the Implementation section for the Ripple API, Sendgrid and the frontend. Please lmk if you agree that it is finished.
