### ISSUE TITLE
Add amount of XRP to account

### ISSUE THREAD

**Issue by jwbambacht** [roemba/xsplit#68]
Fill account with some XRP to simulate the function of buying some XRP by means of IDeal, creditcard, or ...

**Comment by tomdevman** [comment]
Do we need to actually do this on our application ? I taught people were just supposed to be splitting bills not also add XRP credits to their accounts from within our app.

**Comment by jeysbach** [comment]
I don't think we discussed this as a feature. 
We could do it if we have time but I would leave it for later.
