### ISSUE TITLE
Make it possible to set email preferences on accounts page for which events to receive a mail

### ISSUE THREAD

**Issue by roemba** [roemba/xsplit#83]

**Comment by tomdevman** [comment]
I think for this we also need some fields to be added on the account page. @jwbambacht could you have a look over what needs to be done on the frontend for this ? I will continue working on handling the logic on the backend (we might even need to update the User model with some extra fields for storing the preferences).

**Comment by jwbambacht** [comment]
> I think for this we also need some fields to be added on the account page. @jwbambacht could you have a look over what needs to be done on the frontend for this ? I will continue working on handling the logic on the backend (we might even need to update the User model with some extra fields for storing the preferences).

For now setting a general notification preference should be enough. Maybe at a later point we could specify it more. Included in PR #88.

**Comment by tomdevman** [comment]
I added the checks in the `NotificationService` to see whether the user has notifications enabled prior to sending the email. PR #104
